### ISSUE TITLE
folder in workspace isn't matching the files in my repo

### ISSUE THREAD

**Issue by Claire-Crawford** [Claire-Crawford/myWebBiz#26]
Not sure how to describe the issue. I'll do my best . 

I hadn't worked on my site since days before Thanksgiving (since we worked together) and decided to clean up more code thursday morning.  I opened vs code and added myWebBiz folder to my workspace. It's the only folder I have in my Github folder (in documents).  I opened the index file and then opened it up to view in my browser.  I noticed right away that some things were broken on the services page and things were broken in the footer on all pages ... and a few other things here and there were broken.  I hadn't changed a thing and it was all in perfect shape the last time I worked on it .. which was the last time you and I were screensharing and you helped me with a small issue.   So I opened up my site on Netlify and it was perfect, nothing broken.  I noticed that the services file in github had all the correct html code and everything that was broken was due to the fact that code was missing from main.scss.  I opened the files in my github repo and noticed the main.scss file was also missing all the styling codes for the things that are broken on my browser preview.  When I inspect the code on my Netlify site, all the styling code is there, showing up in the main.scss file.   But those styling codes are not in my documents file or the file in my repo(in the main.scss files) .  How can they only be on the site that is hosted by Netlify and nowhere else? So frustrating.  I can't move forward until I figure this out.

**Comment by comaldave** [comment]
I will setup conf, let me look at your machine.

**Comment by comaldave** [comment]
The problem was that the SASS command terminal window had been closed and the CSS was not the current SCSS. Problem Resolved. Close #26
